# Generated by Django 5.2.17 on 2026-09-25 15:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('REQUESTER', 'Requester (Technician / Contractor Supervisor)'), ('AREA_OWNER', 'Area Owner'), ('SAFETY_OFFICER', 'Safety Officer'), ('ADMIN', 'System Admin')], default='REQUESTER', help_text='Role determining permissions and actions', max_length=30)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('badge_number', models.CharField(blank=True, default='', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'role': 'AREA_OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_areas', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='permits.plant')),
            ],
            options={
                'unique_together': {('plant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag_number', models.CharField(max_length=100, unique=True)),
                ('criticality', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High / Critical')], default='MEDIUM', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='permits.area')),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('permit_type', models.CharField(choices=[('HOT_WORK', 'Hot Work'), ('CONFINED_SPACE', 'Confined Space Entry'), ('HEIGHT', 'Working at Height'), ('ELECTRICAL_LOTO', 'Electrical / Isolation (LOTO)'), ('EXCAVATION', 'Excavation & Trenching')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contractor_name', models.CharField(max_length=255)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('planned_start', models.DateTimeField(db_index=True)),
                ('planned_end', models.DateTimeField(db_index=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('CLOSED', 'Closed'), ('CLOSED_VERIFIED', 'Closed & Verified'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=32)),
                ('hazards', models.JSONField(default=list, help_text='List of hazard tags identified')),
                ('ppe_required', models.JSONField(default=list, help_text='List of PPE mandatory for this permit')),
                ('precautions', models.JSONField(default=list, help_text='List of safety precaution items checked')),
                ('type_data', models.JSONField(default=dict, help_text='Type-specific fields validated against schema')),
                ('extension_hours', models.PositiveIntegerField(default=0)),
                ('extension_reason', models.TextField(blank=True, default='')),
                ('extension_requested_at', models.DateTimeField(blank=True, null=True)),
                ('extension_status', models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=20)),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_verified_at', models.DateTimeField(blank=True, null=True)),
                ('closure_verification_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closure_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_closures', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='permits.equipment')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_permits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('actor_role', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='permits.permit')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PermitApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('AREA_OWNER', 'Area Owner'), ('SAFETY_OFFICER', 'Safety Officer')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('signature_data', models.TextField(blank=True, default='', help_text='Base64 canvas drawn signature')),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_approvals', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='permits.permit')),
            ],
            options={
                'unique_together': {('permit', 'role_type')},
            },
        ),
    ]
