# Generated by Django 5.2.17 on 2026-09-26 08:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=150)),
                ('task_description', models.TextField()),
                ('hours_spent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('logged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='permits.permit')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logged_works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
